apiVersion: v2
appVersion: 1.101.2
name: opencost
description: OpenCost and OpenCost UI
type: application
keywords:
  - cost-optimization
  - finops
  - kubecost
  - opencost
  - monitoring
version: 1.6.0
maintainers:
  - name: mattray
    url: https://mattray.dev
