apiVersion: v2
appVersion: 1.117.3
name: opencost
description: OpenCost and OpenCost UI
type: application
keywords:
  - cloud-costs
  - cost-optimization
  - finops
  - monitoring
  - opencost
version: 2.2.6
maintainers:
  - name: jessegoodier
  - name: toscott
  - name: mittal-ishaan
  - name: brito-rafa
    email: rafa@stormforge.io
home: https://github.com/opencost/opencost-helm-chart