apiVersion: v2
appVersion: 1.114.0
name: opencost
description: OpenCost and OpenCost UI
type: application
keywords:
  - cloud-costs
  - cost-optimization
  - finops
  - monitoring
  - opencost
version: 1.44.1
maintainers:
  - name: jessegoodier
  - name: toscott
  - name: mittal-ishaan
  - name: brito-rafa
    email: rafa@stormforge.io
home: https://github.com/opencost/opencost-helm-chart
