apiVersion: v2
appVersion: 1.107.1
name: opencost
description: OpenCost and OpenCost UI
type: application
keywords:
  - cost-optimization
  - finops
  - kubecost
  - opencost
  - monitoring
version: 1.28.0
maintainers:
  - name: mattray
    url: https://mattray.dev
  - name: toscott
home: https://github.com/opencost/opencost-helm-chart
