apiVersion: v2
appVersion: 1.102.0
name: opencost
description: OpenCost and OpenCost UI
type: application
keywords:
  - cost-optimization
  - finops
  - kubecost
  - opencost
  - monitoring
version: 1.13.0
maintainers:
  - name: mattray
    url: https://mattray.dev
  - name: toscott
