{{- include  "isPrometheusConfigValid" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
  name: {{ include "opencost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opencost.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "opencost.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "opencost.serviceAccountName" . }}
      tolerations:
        {{- toYaml .Values.opencost.tolerations | nindent 8 }}
      {{- with .Values.opencost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opencost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with.Values.opencost.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.opencost.exporter.image.registry }}/{{ .Values.opencost.exporter.image.repository }}:{{ .Values.opencost.exporter.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          name: {{ include "opencost.fullname" . }}
          resources:
            {{- toYaml .Values.opencost.exporter.resources | nindent 12 }}
          ports:
            - containerPort: 9003
              name: http
          volumeMounts:
          {{- if .Values.opencost.exporter.extraVolumeMounts }}
          {{- toYaml .Values.opencost.exporter.extraVolumeMounts | nindent 12 }}
          {{- end }}
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: {{ include "opencost.prometheusServerEndpoint" . | quote }}
            {{- if .Values.opencost.exporter.cloudProviderApiKey }}
            - name: CLOUD_PROVIDER_API_KEY
              value: {{ .Values.opencost.exporter.cloudProviderApiKey | quote }}
            {{- end }}
            - name: CLUSTER_ID
              value: {{ .Values.opencost.exporter.defaultClusterId | quote }}
            # If username, password or bearer_token are defined, pull from secrets
            {{- if .Values.opencost.prometheus.username }}
            - name: DB_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BASIC_AUTH_USERNAME
            {{- end }}
            {{- if .Values.opencost.prometheus.password }}
            - name: DB_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BASIC_AUTH_PW
            {{- else if .Values.opencost.prometheus.bearer_token }}
            - name: DB_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BEARER_TOKEN
            {{- end }}
            # Add any additional provided variables
            {{- range $key, $value := .Values.opencost.exporter.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          imagePullPolicy: Always
        {{- if .Values.opencost.ui.enabled }}
        - image:  "{{ .Values.opencost.ui.image.registry }}/{{ .Values.opencost.ui.image.repository }}:{{ .Values.opencost.ui.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          name: opencost-ui
          resources:
            {{- toYaml .Values.opencost.ui.resources | nindent 12 }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: http-ui
        {{- end }}
      volumes:
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
