{{- include  "isPrometheusConfigValid" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencost.fullname" . }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.opencost.exporter.replicas }}
  selector:
    matchLabels: {{- include "opencost.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "opencost.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "opencost.serviceAccountName" . }}
      {{- with .Values.opencost.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opencost.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opencost.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with.Values.opencost.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "opencost.fullname" . }}
          image: "{{ .Values.opencost.exporter.image.registry }}/{{ .Values.opencost.exporter.image.repository }}:{{ .Values.opencost.exporter.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.opencost.exporter.image.pullPolicy }}
          ports:
            - containerPort: 9003
              name: http
          resources: {{- toYaml .Values.opencost.exporter.resources | nindent 12 }}
          {{- if .Values.opencost.exporter.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: {{ .Values.opencost.exporter.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.opencost.exporter.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.opencost.exporter.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.opencost.exporter.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: {{ .Values.opencost.exporter.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.opencost.exporter.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.opencost.exporter.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.opencost.exporter.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: {{ include "opencost.prometheusServerEndpoint" . | quote }}
            {{- if .Values.opencost.exporter.cloudProviderApiKey }}
            - name: CLOUD_PROVIDER_API_KEY
              value: {{ .Values.opencost.exporter.cloudProviderApiKey | quote }}
            {{- end }}
            - name: CLUSTER_ID
              value: {{ .Values.opencost.exporter.defaultClusterId | quote }}
            {{- if .Values.opencost.exporter.aws.access_key_id }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.prometheus.secretname" . }}
                  key: AWS_ACCESS_KEY_ID
            {{- end }}
            {{- if .Values.opencost.exporter.aws.secret_access_key }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.prometheus.secretname" . }}
                  key: AWS_SECRET_ACCESS_KEY
            {{- end }}
            # If username, password or bearer_token are defined, pull from secrets
            {{- if or .Values.opencost.prometheus.username (and .Values.opencost.prometheus.secret_name .Values.opencost.prometheus.username_key) }}
            - name: DB_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.prometheus.secretname" . }}
                  key: {{ .Values.opencost.prometheus.username_key }}
            {{- end }}
            {{- if or .Values.opencost.prometheus.password (and .Values.opencost.prometheus.secret_name .Values.opencost.prometheus.password_key) }}
            - name: DB_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.prometheus.secretname" . }}
                  key: {{ .Values.opencost.prometheus.password_key }}
            {{- else if or .Values.opencost.prometheus.bearer_token (and .Values.opencost.prometheus.secret_name .Values.opencost.prometheus.bearer_token_key) }}
            - name: DB_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.prometheus.secretname" . }}
                  key: {{ .Values.opencost.prometheus.bearer_token_key }}
            {{- end }}
            {{- if and .Values.opencost.exporter.persistence.enabled .Values.opencost.exporter.csv_path }}
            - name: EXPORT_CSV_FILE
              value: {{ .Values.opencost.exporter.csv_path | quote }}
            {{- end}}
            {{- with .Values.opencost.exporter.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- range $key, $value := .Values.opencost.exporter.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if or .Values.opencost.exporter.persistence.enabled .Values.opencost.exporter.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.opencost.exporter.persistence.enabled }}
            - mountPath: /mnt/export
              name: opencost-export
              readOnly: false
            {{- end }}
            {{- with .Values.opencost.exporter.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- if .Values.opencost.ui.enabled }}
        - name: opencost-ui
          image:  "{{ .Values.opencost.ui.image.registry }}/{{ .Values.opencost.ui.image.repository }}:{{ .Values.opencost.ui.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.opencost.ui.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: http-ui
          resources: {{- toYaml .Values.opencost.ui.resources | nindent 12 }}
          {{- if .Values.opencost.ui.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: {{ .Values.opencost.ui.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.opencost.ui.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.opencost.ui.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.opencost.ui.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: {{ .Values.opencost.ui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.opencost.ui.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.opencost.ui.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.opencost.ui.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.opencost.ui.extraVolumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if or .Values.opencost.exporter.persistence.enabled .Values.extraVolumes }}
      volumes:
        {{- if .Values.opencost.exporter.persistence.enabled }}
        - name: opencost-export
          persistentVolumeClaim:
            claimName: {{ include "opencost.fullname" . }}-pvc
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
