{{- include  "isPrometheusConfigValid" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
  name: {{ include "opencost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.opencost.exporter.replicas }}
  selector:
    matchLabels:
      {{- include "opencost.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "opencost.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ template "opencost.serviceAccountName" . }}
      tolerations:
        {{- toYaml .Values.opencost.tolerations | nindent 8 }}
      {{- with .Values.opencost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.opencost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with.Values.opencost.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.opencost.exporter.image.registry }}/{{ .Values.opencost.exporter.image.repository }}:{{ .Values.opencost.exporter.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          name: {{ include "opencost.fullname" . }}
          resources:
            {{- toYaml .Values.opencost.exporter.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 200
          {{- with .Values.opencost.exporter.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          {{- with .Values.opencost.exporter.redinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 9003
              name: http
          securityContext:
            {{- toYaml .Values.opencost.exporter.securityContext | nindent 12 }}
          {{- with .Values.opencost.exporter.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: {{ include "opencost.prometheusServerEndpoint" . | quote }}
            {{- if .Values.opencost.exporter.cloudProviderApiKey }}
            - name: CLOUD_PROVIDER_API_KEY
              value: {{ .Values.opencost.exporter.cloudProviderApiKey | quote }}
            {{- end }}
            - name: CLUSTER_ID
              value: {{ .Values.opencost.exporter.defaultClusterId | quote }}
            {{- if .Values.opencost.exporter.aws.access_key_id }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: AWS_ACCESS_KEY_ID
            {{- end }}
            {{- if .Values.opencost.exporter.aws.secret_access_key }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: AWS_SECRET_ACCESS_KEY
            {{- end }}
            # If username, password or bearer_token are defined, pull from secrets
            {{- if .Values.opencost.prometheus.username }}
            - name: DB_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BASIC_AUTH_USERNAME
            {{- end }}
            {{- if .Values.opencost.prometheus.password }}
            - name: DB_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BASIC_AUTH_PW
            {{- else if .Values.opencost.prometheus.bearer_token }}
            - name: DB_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencost.fullname" . }}
                  key: DB_BEARER_TOKEN
            {{- end }}
            {{- if and .Values.opencost.exporter.persistence.enabled .Values.opencost.exporter.csv_path }}
            - name: EXPORT_CSV_FILE
              value: {{ .Values.opencost.exporter.csv_path | quote }}
            {{- end}}
            {{- with .Values.opencost.exporter.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            # Add any additional provided variables
            {{- range $key, $value := .Values.opencost.exporter.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.opencost.exporter.persistence.enabled }}
          volumeMounts:
            - mountPath: /mnt/export
              name: opencost-export
              readOnly: false
          {{- end }}
          imagePullPolicy: Always
        {{- if .Values.opencost.ui.enabled }}
        - image:  "{{ .Values.opencost.ui.image.registry }}/{{ .Values.opencost.ui.image.repository }}:{{ .Values.opencost.ui.image.tag | default (printf "prod-%s" .Chart.AppVersion) }}"
          name: opencost-ui
          {{- with .Values.opencost.ui.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          {{- with .Values.opencost.ui.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.opencost.ui.resources | nindent 12 }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: http-ui
          securityContext:
            {{- toYaml .Values.opencost.ui.securityContext | nindent 12 }}
          {{- with .Values.opencost.ui.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
      {{- if .Values.opencost.exporter.persistence.enabled }}
        - name: opencost-export
          persistentVolumeClaim:
            claimName: {{ include "opencost.fullname" . }}-pvc
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
