{{- if .Values.opencost.cloudIntegrationJSON }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opencost.cloudIntegration.secretName" . }}
  namespace: {{ include "opencost.namespace" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
data:
  cloud-integration.json: {{ .Values.opencost.cloudIntegrationJSON | trimSuffix "\n" | b64enc | quote }}
{{- end }}
