{{- if or .Values.opencost.prometheus.username .Values.opencost.prometheus.password .Values.opencost.prometheus.bearer_token .Values.opencost.exporter.aws.access_key_id -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
  name: {{ include "opencost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.opencost.prometheus.username }}
  DB_BASIC_AUTH_USERNAME: {{ .Values.opencost.prometheus.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.opencost.prometheus.password }}
  DB_BASIC_AUTH_PW: {{ .Values.opencost.prometheus.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.opencost.prometheus.bearer_token }}
  DB_BEARER_TOKEN: {{ .Values.opencost.prometheus.bearer_token | b64enc | quote }}
  {{- end }}
  {{- if .Values.opencost.exporter.aws.access_key_id }}
  AWS_ACCESS_KEY_ID: {{ .Values.opencost.exporter.aws.access_key_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.opencost.exporter.aws.access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.opencost.exporter.aws.secret_access_key | b64enc | quote }}
  {{- end }}
{{- end }}
