{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "opencost.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 9003
      targetPort: 9003
    {{- if .Values.opencost.ui.enabled }}
    - name: http-ui
      port: 9090
      targetPort: 9090
    {{- end }}
{{- end }}
